server:
  port: 8080

spring:
  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    url: jdbc:oracle:thin:@//avdf01.rh:2019/rayannav21c.rh
    driverClassName: oracle.jdbc.OracleDriver
    username: N21AATF01
    password: n
#    username: masoud
#    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwtSecret: xDnbM0I6G6hnT9uaFBIX8pKdhPkyA4JRlG7nqPQ4GM0=
  jwtExpirationInMs: 86400000 # 24 hours
  authSecret: de2B5QnArtdSuVaEpSXTDT84YsEqSdoHPz3ewk7MWMU=

external:
  validation:
    url: http://external-validation-service/api/validate

sms:
  provider:
    url: http://sms-gateway/api/send
    apiKey: your-sms-api-key