server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    driverClassName: oracle.jdbc.OracleDriver
    username: masoud
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 86400000 # 24 hours

external:
  validation:
    url: http://external-validation-service/api/validate

sms:
  provider:
    url: http://sms-gateway/api/send
    apiKey: your-sms-api-key